### PR TITLE
Incorporate all SEP examples

### LINKED ISSUE #122: Incorporate all SEP examples into specification
The examples section of the specification is still somewhat thin. There are a number of SEPs that, either in the SEP itself or in the discussion around it, included good examples that have not been incorporated into the specification. Somebody should cull through all of the SEPs and make sure that they are all included.

### PR DESCRIPTION
**Pull request by jakebeal**
Fix #122 by incorporating all significant missing SEP examples into the specification, also updating examples that had obsolete glyphs.

### CODE REVIEW

**Review by hasanbaig — COMMENTED** [review]
In line 120 (in apd-examples.tex file) , there is an extra SPACE between words "codon" and "at". kindly fix it.

**Review by hasanbaig — COMMENTED** [review]
In Line 112, should not the figure be pointing to "apdx-exa**19**-stop-sites.pdf}". 

There is no file "apdx-exa18-stop-sites" in the specified directory.

**Comment by hasanbaig** [comment]
> In Line 112, should not the figure be pointing to "apdx-exa**19**-stop-sites.pdf}".
> 
> There is no file "apdx-exa18-stop-sites" in the specified directory.

Please also check similar issues in other file paths.

**Comment by jakebeal** [comment]
I fixed the double space, though it doesn't actually show up in the produced document since LaTeX doesn't care about number of spaces.

For the figure references --- which commit are you looking at?  In the current commit, it does have the references that you were asking for, which I've verified by compiling the LaTeX.

**Comment by hasanbaig** [comment]
> I fixed the double space, though it doesn't actually show up in the produced document since LaTeX doesn't care about number of spaces.
> 
> For the figure references --- which commit are you looking at? In the current commit, it does have the references that you were asking for, which I've verified by compiling the LaTeX.

I checked all the commits in sequence and the one I was referring to was "[0af5eb4](https://github.com/SynBioDex/SBOL-visual/pull/131/commits/0af5eb4a6ddd478eeddbe80f9176aa7704a5ff38)"

**Comment by hasanbaig** [comment]
> I fixed the double space, though it doesn't actually show up in the produced document since LaTeX doesn't care about number of spaces.
> 
> For the figure references --- which commit are you looking at? In the current commit, it does have the references that you were asking for, which I've verified by compiling the LaTeX.

I don't see any other things. It is good to be merged now.

**Comment by jakebeal** [comment]
Ah, yes: if you look at individual commits, there will often be issues that were resolved before the pull request is submitted.  That's why I usually use the "files changed" instead of "commits", which shows the final state only.

Thank you for the review; I will merge!

**Pull request merged**
