### PR TITLE
Merge ontology update into 2.2 pre-release

### PR DESCRIPTION
**Pull request by jakebeal**
Need to review all aspects of the ontology update to make sure they are reflected in the specification, and vice versa

### CODE REVIEW

**Comment by goksel** [comment]
@jakebeal I am listed as a reviewer for this pull request and I just wanted to double check if there is anything in particular you want me to review.

**Comment by jakebeal** [comment]
@goksel I'd like you to check and make sure the current state of the ontology and the specification match one another --- I'm not sure if the specification has had any updates since your more recent ontology commit.

**Review by goksel — APPROVED** [review]
The ontology has been developed using the latest updates to he README files. I went through the commit history to double check. The spec related issues were created as part of the issue 15 (https://github.com/SynBioDex/SBOL-visual/issues/15) and they were resolved and incorporated into the SBOL Visual ontology. The ontology is created using scripts. If there is any issue, we can re-run the scripts in the future. The naming of terms are currently based on human readable labels, e.g. AptamerGlyph. It may be useful to discuss this perhaps in the SBOL Visual emailing list. 

There is one remaining task: To merge the ontology-update feature branch into the master branch.

**Comment by jakebeal** [comment]
Thank you, Goskel; I've merged into develop.  The master branch merge will happen with the 2.2 release, sometime within the next two months.

**Pull request merged**
