### PR TITLE
Draft adjustment of ontology to organize glyphs into four classes

### PR DESCRIPTION
**Pull request by jakebeal**
Per issue #96, I have created a draft adjustment of the ontology that organizes all glyphs into the four subclasses provided by the ontology.

This still needs verification and also regeneration of HTML.  @goksel , can you please instruct on how to do that? I do not find anything in the README at present.

### CODE REVIEW

**Comment by cjmyers** [comment]
@goksel can you review this one?

**Comment by goksel** [comment]
Jake, apologies, I should have done this already. The changes look ok. However,tThe SBOL Visual Ontology is autogenerated. Do we want to start manually updating the ontology or shall I update the ontology via the script which uses after the Glyph directory files when generating the ontology?

**Comment by jakebeal** [comment]
@goksel I'd like to go with a third option: can you please add documentation and any missing code to the repository so that others (including me) can run the autogeneration?

Expanding the update workflow to include the ontology is one of the big goals that I'd like to see accomplished between now and the end of COMBINE.

**Comment by jakebeal** [comment]
Closing in favor of #106

**Pull request closed without merging**
